/**
 * surveyExamples.ts — exemplos de resposta (placeholders) por SEGMENTO (niche).
 *
 * Por que existe: os placeholders do survey global (surveyTypes.ts) foram
 * escritos com exemplos de odontologia ("Ex: Clínica Sorriso Perfeito"). Pra um
 * restaurante, pet shop etc. isso fica errado. Aqui mapeamos, por niche e por
 * id da pergunta, um exemplo RELEVANTE — resolvido em runtime pelo niche da org.
 *
 * Estratégia (Fase 1):
 *   - GENERIC: exemplos NEUTROS (não amarrados a nenhum segmento) para as
 *     perguntas mais "cara-de-dentista". Garante que nenhum cliente veja exemplo
 *     de outro segmento, mesmo antes do seu niche ter set próprio.
 *   - NICHE_EXAMPLES[niche]: exemplos específicos do segmento (começamos por
 *     'restaurante'; os demais nichos entram em ondas seguintes).
 *
 * Resolução: examplePlaceholder(niche, id, fallbackOriginal)
 *   = NICHE_EXAMPLES[niche]?.[id] ?? GENERIC[id] ?? fallbackOriginal
 *
 * Niches válidos (key de surveySegments): academia, dentista, psicólogo,
 * advogado, nutricionista, salao, petshop, imobiliaria, restaurante, escola,
 * servicos_tecnicos, clinica_medica, contabilidade, oficina, agencia_digital,
 * ecommerce.
 */

type Examples = Record<string, string>;

// ── Neutros (qualquer segmento) — usados quando o niche ainda não tem set ────
const GENERIC: Examples = {
  ide_nome_fantasia: 'Ex: o nome que seus clientes usam pra te encontrar',
  ide_razao_social: 'Ex: Razão Social da sua empresa Ltda.',
  pos_proposta_valor: 'Ex: o que você entrega de melhor e por que os clientes escolhem você',
  pos_diferenciais: 'Ex:\n1. Diferencial nº 1\n2. Diferencial nº 2\n3. Diferencial nº 3',
  pos_dor_principal: 'Ex: o principal problema que seu cliente tem e que você resolve',
  pos_concorrentes: 'Ex:\n1. Concorrente A — foco em preço\n2. Concorrente B — referência no bairro',
  pos_diferencial_vs_concorrentes: 'Ex: o que só você faz e os concorrentes não',
  pos_jargoes_setor: 'Ex: termos técnicos do seu setor que a IA deve conhecer',
  pos_slogan: 'Ex: a frase que resume seu negócio',
  pos_historia_marca: 'Ex: como e por que o negócio começou',
  pos_o_que_nao_somos: 'Ex: o que seu negócio NÃO faz / NÃO atende',
  pos_como_ser_percebida: 'Ex: confiável, moderna, acolhedora',
  pub_perfil_ideal: 'Ex: idade, perfil, o que valoriza, onde está',
  pub_perfil_secundario: 'Ex: um segundo público relevante',
  pub_perfil_nao_desejado: 'Ex: o tipo de cliente que não é o seu',
  pub_ticket_medio: 'Ex: valor médio que um cliente gasta',
  pub_dores_comuns: 'Ex:\n1. Dor mais comum\n2. Segunda dor\n3. Terceira dor',
  pub_objecoes_comuns: 'Ex:\n1. "Está caro"\n2. "Vou pensar"\n3. "Preciso ver com alguém"',
  tom_nome_ia: 'Ex: um nome próprio para sua IA (ou deixe em branco)',
  tom_cumprimento: 'Ex: como a IA cumprimenta na primeira mensagem',
  com_lista_servicos: 'Ex: liste seus principais produtos/serviços e faixas de preço',
  com_categorias: 'Ex: como seus produtos/serviços se agrupam',
  com_servico_entrada: 'Ex: o produto/serviço de entrada (porta de entrada)',
  com_maior_margem: 'Ex: o serviço/produto de maior margem',
  com_maior_volume: 'Ex: o serviço/produto que mais vende',
  com_servico_premium: 'Ex: seu serviço/produto premium e o preço',
  com_combos_pacotes: 'Ex: combos ou pacotes que você oferece',
  com_garantia: 'Ex: qual garantia você oferece e por quanto tempo',
  qual_objecao_preco: 'Ex: como responder quando o cliente acha caro',
  pre_tabela_precos: 'Ex: sua tabela de preços principal',
  pre_parcelamento: 'Ex: formas de pagamento e parcelamento',
  faq_perguntas_frequentes: 'Ex:\nP: pergunta comum?\nR: resposta padrão',
  faq_contraindicacoes: 'Ex: restrições ou casos que você não atende',
  crm_tags: 'Ex: #lead-quente, #cliente-fiel, #orcamento, #retorno',
  crm_ltv: 'Ex: quanto um cliente gasta ao longo do relacionamento',
};

// ── Restaurante (Fase 1 — caso piloto Ghetti Italian Food) ───────────────────
const restaurante: Examples = {
  ide_nome_fantasia: 'Ex: Restaurante Dona Maria',
  ide_razao_social: 'Ex: Dona Maria Alimentos Ltda.',
  pos_proposta_valor: 'Ex: Comida caseira italiana, massa fresca feita na hora e ambiente familiar.',
  pos_diferenciais: 'Ex:\n1. Massa fresca produzida no dia\n2. Receitas de família há 30 anos\n3. Delivery em até 40 min na região',
  pos_dor_principal: 'Ex: Clientes que querem comer bem sem cozinhar e cansaram de fast-food sem qualidade.',
  pos_concorrentes: 'Ex:\n1. Cantina do Centro — foco em preço baixo\n2. Trattoria Bella — referência em massas\n3. Rede de pizzarias — muitas unidades',
  pos_diferencial_vs_concorrentes: 'Ex: Ao contrário das redes, aqui a massa é fresca e o molho é feito todo dia.',
  pos_jargoes_setor: 'Ex: "couvert", "rodízio", "à la carte", "mise en place", "delivery", "comanda"',
  pos_slogan: 'Ex: "O sabor da Itália pertinho de você."',
  pos_historia_marca: 'Ex: "Fundado em 1995 pela nona Maria, que trouxe as receitas da Calábria."',
  pos_o_que_nao_somos: 'Ex: Não fazemos comida congelada. Não atendemos eventos acima de 100 pessoas. Não temos opção self-service.',
  pos_como_ser_percebida: 'Ex: acolhedor, autêntico, caseiro, de confiança',
  pub_perfil_ideal: 'Ex: Famílias e casais 30-55 anos que valorizam comida boa e ambiente aconchegante.',
  pub_perfil_secundario: 'Ex: Empresas da região buscando almoço executivo no dia a dia.',
  pub_perfil_nao_desejado: 'Ex: Quem busca só o prato mais barato e reclama de couvert.',
  pub_ticket_medio: 'Ex: R$ 70 por pessoa no jantar, R$ 45 no almoço executivo',
  pub_dores_comuns: 'Ex:\n1. Não saber o tempo de entrega\n2. Dúvida se tem opção sem glúten\n3. Achar que vai demorar pra ser atendido',
  pub_objecoes_comuns: 'Ex:\n1. "A entrega demora?"\n2. "Tem opção vegetariana?"\n3. "O couvert é obrigatório?"',
  tom_nome_ia: 'Ex: "Bella", "Atendente do Dona Maria", deixe em branco se preferir sem nome',
  tom_cumprimento: 'Ex: "Olá! 😊 Bem-vindo(a) ao Restaurante Dona Maria! Quer ver o cardápio ou fazer um pedido?"',
  com_lista_servicos: 'Ex:\n- Rodízio de massas (R$ 79)\n- Pizza individual (R$ 35-55)\n- Almoço executivo (R$ 39,90)\n- Sobremesas artesanais (R$ 18-25)',
  com_categorias: 'Ex:\n- Entradas: bruschetta, antepasto\n- Massas: nhoque, ravioli, lasanha\n- Pizzas\n- Sobremesas e bebidas',
  com_servico_entrada: 'Ex: Almoço executivo do dia — preço acessível pra atrair cliente novo',
  com_maior_margem: 'Ex: Vinhos e sobremesas — margem acima de 65%',
  com_maior_volume: 'Ex: Almoço executivo — 50% dos pedidos no almoço',
  com_servico_premium: 'Ex: Jantar harmonizado com vinhos — R$ 250 por pessoa',
  com_combos_pacotes: 'Ex:\n- Combo Casal (2 massas + 1 sobremesa + 1 vinho) R$ 159\n- Almoço executivo (prato + bebida + sobremesa) R$ 49,90',
  com_garantia: 'Ex: Se o prato vier errado ou frio, refazemos na hora — sem custo.',
  qual_objecao_preco: 'Ex: Destacar a porção generosa, a massa fresca e o combo casal que sai mais em conta.',
  pre_tabela_precos: 'Ex:\n- Almoço executivo: R$ 39,90\n- Rodízio de massas: R$ 79\n- Pizza grande: R$ 55-75\n- Delivery: pedido mínimo R$ 30',
  pre_parcelamento: 'Ex: Crédito, débito, Pix e VR/VA. Acima de R$ 200, parcela em 2x sem juros.',
  faq_perguntas_frequentes: 'Ex:\nP: Fazem delivery?\nR: Sim, pelo iFood e pelo nosso WhatsApp, entrega em até 40 min.\nP: Tem opção sem glúten?\nR: Sim, massas sem glúten sob consulta.',
  faq_contraindicacoes: 'Ex: Alguns pratos contêm glúten, lactose e frutos do mar — sempre avisar. Temos opções veganas e sem glúten.',
  crm_tags: 'Ex: #delivery, #reserva, #aniversariante, #cliente-fiel, #evento, #vegetariano',
  crm_ltv: 'Ex: R$ 2.400 por ano (cliente que volta ~2x por mês)',
};

// ── Odontologia (dentista) ───────────────────────────────────────────────────
const dentista: Examples = {
  ide_nome_fantasia: 'Ex: Clínica Sorriso Perfeito',
  ide_razao_social: 'Ex: Sorriso Perfeito Odontologia Ltda.',
  pos_proposta_valor: 'Ex: Odontologia humanizada, sem dor e com tecnologia de ponta — do clareamento ao implante.',
  pos_diferenciais: 'Ex:\n1. Atendimento sem fila — horário respeitado\n2. Sedação para pacientes com medo\n3. Parcelamento em até 24x\n4. Scanner intraoral (sem moldagem)',
  pos_dor_principal: 'Ex: Pessoas que têm medo de dentista e adiam tratamentos por anos.',
  pos_concorrentes: 'Ex:\n1. Clínica popular — foco em preço\n2. Dr. Silva — referência em implante\n3. Rede de franquias odontológicas',
  pos_jargoes_setor: 'Ex: "canal", "prótese", "aparelho fixo", "clareamento", "faceta", "implante", "profilaxia"',
  pos_slogan: 'Ex: "Seu sorriso, nossa missão."',
  pos_o_que_nao_somos: 'Ex: Não atendemos emergência 24h. Não fazemos ortodontia infantil. Não aceitamos convênios.',
  pub_perfil_ideal: 'Ex: Adultos 30-55 anos, classe B, que valorizam estética e atendimento sem dor.',
  pub_perfil_nao_desejado: 'Ex: Quem busca só o orçamento mais barato e não valoriza qualidade clínica.',
  pub_ticket_medio: 'Ex: R$ 350 por consulta; R$ 4.500 por tratamento de implante.',
  pub_dores_comuns: 'Ex:\n1. Medo de sentir dor\n2. Preço alto / como parcelar\n3. Não saber qual tratamento precisa\n4. Vergonha do sorriso',
  pub_objecoes_comuns: 'Ex:\n1. "Está caro"\n2. "Vou pensar"\n3. "Dói?"\n4. "Aceita meu convênio?"',
  tom_cumprimento: 'Ex: "Olá! 😊 Seja bem-vindo(a) à Clínica Sorriso Perfeito! Em que posso ajudar com seu sorriso?"',
  com_lista_servicos: 'Ex:\n- Avaliação (gratuita)\n- Limpeza (R$ 180)\n- Clareamento (R$ 800-1.500)\n- Implante (a partir de R$ 3.500)\n- Aparelho ortodôntico',
  com_categorias: 'Ex:\n- Estética: clareamento, facetas, lentes\n- Reabilitação: implante, prótese\n- Ortodontia: aparelho\n- Preventiva: limpeza',
  com_servico_premium: 'Ex: Protocolo de implante completo — R$ 25.000',
  com_combos_pacotes: 'Ex: Pacote Sorriso (avaliação + limpeza + clareamento) R$ 1.200',
  com_garantia: 'Ex: Implante com garantia vitalícia do pino; faceta com 5 anos.',
  qual_objecao_preco: 'Ex: Mostrar parcelamento em 24x, comparar com o custo de não tratar e oferecer avaliação gratuita.',
  pre_tabela_precos: 'Ex:\n- Consulta inicial: gratuita\n- Limpeza: R$ 180\n- Clareamento: R$ 800-1.500\n- Implante: a partir de R$ 3.500',
  pre_parcelamento: 'Ex: Até 24x no cartão; entrada + boleto; desconto à vista no Pix.',
  faq_perguntas_frequentes: 'Ex:\nP: Aceita convênio?\nR: Trabalhamos com particular e alguns convênios — confirme o seu.\nP: Dói?\nR: Usamos anestesia e sedação; o conforto é prioridade.\nP: Parcela?\nR: Sim, até 24x.',
  faq_contraindicacoes: 'Ex: Gestantes não fazem clareamento; diabéticos precisam de avaliação antes de cirurgia.',
  crm_tags: 'Ex: #lead-quente, #implante, #ortodontia, #clareamento, #retorno, #convenio',
  crm_ltv: 'Ex: R$ 6.000 ao longo de 3 anos (tratamentos + manutenção).',
};

// ── Salão de beleza / barbearia (salao) ──────────────────────────────────────
const salao: Examples = {
  ide_nome_fantasia: 'Ex: Studio Bella Hair',
  ide_razao_social: 'Ex: Bella Hair Beleza e Estética Ltda.',
  pos_proposta_valor: 'Ex: Beleza e autoestima em um ambiente acolhedor, com profissionais especializados em coloração e tratamentos.',
  pos_diferenciais: 'Ex:\n1. Especialistas em loiros e mechas\n2. Produtos profissionais (sem amônia)\n3. Café e wi-fi enquanto espera\n4. Horário marcado, sem espera',
  pos_dor_principal: 'Ex: Clientes cansadas de coloração malfeita e de salão que atrasa o horário.',
  pos_concorrentes: 'Ex:\n1. Salão do bairro — preço baixo\n2. Rede de franquias\n3. Profissional autônoma em casa',
  pos_jargoes_setor: 'Ex: "mechas", "ombré", "progressiva", "matização", "corte repicado", "hidratação", "escova"',
  pos_slogan: 'Ex: "Realçando a sua beleza natural."',
  pos_o_que_nao_somos: 'Ex: Não atendemos sem agendamento. Não fazemos serviços de estética facial. Não vendemos produtos no varejo.',
  pub_perfil_ideal: 'Ex: Mulheres 25-50 anos que cuidam da aparência e valorizam um profissional de confiança.',
  pub_perfil_nao_desejado: 'Ex: Quem só procura o preço mais baixo e remarca em cima da hora.',
  pub_ticket_medio: 'Ex: R$ 180 por visita; R$ 450 quando inclui coloração.',
  pub_dores_comuns: 'Ex:\n1. Medo de errar a cor\n2. Demora no atendimento\n3. Cabelo danificado por química\n4. Não conseguir horário',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto custa a mecha?"\n2. "Tem horário hoje?"\n3. "Vai estragar meu cabelo?"\n4. "Demora quanto?"',
  tom_cumprimento: 'Ex: "Oi, linda! 💇‍♀️ Bem-vinda ao Studio Bella Hair! Quer agendar um horário ou saber sobre nossos serviços?"',
  com_lista_servicos: 'Ex:\n- Corte feminino (R$ 90)\n- Escova (R$ 70)\n- Coloração (R$ 250)\n- Mechas/luzes (R$ 350-600)\n- Progressiva (R$ 280)',
  com_categorias: 'Ex:\n- Cortes\n- Coloração e mechas\n- Tratamentos (hidratação, botox capilar)\n- Finalização (escova, penteado)',
  com_servico_premium: 'Ex: Transformação completa (corte + coloração + tratamento) — R$ 900',
  com_combos_pacotes: 'Ex: Pacote Noiva (teste + dia do casamento) R$ 1.200; Combo Corte + Escova R$ 140',
  com_garantia: 'Ex: Retoque de cor grátis em até 7 dias se não ficar como combinado.',
  qual_objecao_preco: 'Ex: Mostrar a durabilidade do serviço, a qualidade dos produtos e oferecer um combo.',
  pre_tabela_precos: 'Ex:\n- Corte: R$ 90\n- Escova: R$ 70\n- Coloração: R$ 250\n- Mechas: R$ 350-600',
  pre_parcelamento: 'Ex: Pix, débito e crédito; acima de R$ 300 parcela em 2x.',
  faq_perguntas_frequentes: 'Ex:\nP: Precisa agendar?\nR: Sim, trabalhamos com horário marcado.\nP: Quanto custa mechas?\nR: De R$ 350 a R$ 600 conforme o comprimento.\nP: Atende domingo?\nR: Não, de terça a sábado.',
  faq_contraindicacoes: 'Ex: Química em cabelo muito danificado exige avaliação; gestantes só com liberação.',
  crm_tags: 'Ex: #coloracao, #mechas, #cliente-fiel, #noiva, #aniversariante',
  crm_ltv: 'Ex: R$ 3.600/ano (cliente que volta a cada 4-6 semanas).',
};

// ── Academia / fitness (academia) ────────────────────────────────────────────
const academia: Examples = {
  ide_nome_fantasia: 'Ex: PowerFit Academia',
  ide_razao_social: 'Ex: PowerFit Atividades Físicas Ltda.',
  pos_proposta_valor: 'Ex: Treino com acompanhamento de verdade, equipamentos de ponta e ambiente motivador pra você bater suas metas.',
  pos_diferenciais: 'Ex:\n1. Avaliação física e treino individualizado\n2. Aulas coletivas inclusas\n3. App de acompanhamento\n4. Aberto das 5h às 23h',
  pos_dor_principal: 'Ex: Quem quer emagrecer/ganhar massa mas não sabe treinar sozinho e desiste por falta de acompanhamento.',
  pos_concorrentes: 'Ex:\n1. Rede low-cost (só musculação)\n2. Academia de bairro\n3. Personal autônomo',
  pos_jargoes_setor: 'Ex: "hipertrofia", "HIIT", "avaliação física", "ficha de treino", "funcional", "cross", "plano anual"',
  pos_slogan: 'Ex: "Sua melhor versão começa aqui."',
  pos_o_que_nao_somos: 'Ex: Não somos low-cost sem suporte. Não vendemos suplemento. Não temos piscina.',
  pub_perfil_ideal: 'Ex: Adultos 20-45 anos que querem resultado com acompanhamento e aulas variadas.',
  pub_perfil_nao_desejado: 'Ex: Quem só busca a mensalidade mais barata e não usa o acompanhamento.',
  pub_ticket_medio: 'Ex: R$ 130/mês no plano mensal; R$ 99/mês no anual.',
  pub_dores_comuns: 'Ex:\n1. Não saber treinar sozinho\n2. Falta de motivação\n3. Medo de não ter resultado\n4. Horário que cabe na rotina',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto é a mensalidade?"\n2. "Tem fidelidade?"\n3. "Tem aula de spinning?"\n4. "Posso fazer aula experimental?"',
  tom_cumprimento: 'Ex: "Fala! 💪 Bem-vindo(a) à PowerFit! Quer agendar uma aula experimental ou conhecer nossos planos?"',
  com_lista_servicos: 'Ex:\n- Musculação\n- Aulas coletivas (spinning, funcional, jump)\n- Avaliação física\n- Personal trainer\n- Plano anual/mensal',
  com_categorias: 'Ex:\n- Musculação\n- Aulas coletivas\n- Treino personalizado\n- Avaliação e nutrição',
  com_servico_premium: 'Ex: Plano Black (musculação + todas as aulas + personal + avaliação) R$ 299/mês',
  com_combos_pacotes: 'Ex: Plano anual R$ 99/mês; Dupla (2 pessoas) com 15% off; Trimestral R$ 119/mês',
  com_garantia: 'Ex: 7 dias de garantia — não gostou, devolvemos a primeira mensalidade.',
  qual_objecao_preco: 'Ex: Comparar custo/dia, destacar aulas inclusas e oferecer aula experimental gratuita.',
  pre_tabela_precos: 'Ex:\n- Mensal: R$ 130\n- Trimestral: R$ 119/mês\n- Anual: R$ 99/mês\n- Aula avulsa: R$ 30',
  pre_parcelamento: 'Ex: Anual em 12x no cartão; mensal recorrente; Pix com desconto.',
  faq_perguntas_frequentes: 'Ex:\nP: Tem aula experimental?\nR: Sim, grátis! Agende pelo WhatsApp.\nP: Tem fidelidade?\nR: Só no plano anual.\nP: Qual o horário?\nR: Seg-Sex 5h-23h, Sáb 8h-14h.',
  faq_contraindicacoes: 'Ex: Para condições cardíacas ou gestantes, pedimos liberação médica antes de iniciar.',
  crm_tags: 'Ex: #aula-experimental, #plano-anual, #renovacao, #personal, #emagrecimento',
  crm_ltv: 'Ex: R$ 1.400/ano por aluno (mensalidade média × retenção).',
};

// ── Pet shop / veterinário (petshop) ─────────────────────────────────────────
const petshop: Examples = {
  ide_nome_fantasia: 'Ex: Mundo Pet',
  ide_razao_social: 'Ex: Mundo Pet Comércio e Serviços Ltda.',
  pos_proposta_valor: 'Ex: Cuidado completo pro seu pet em um só lugar: banho & tosa, veterinário e produtos, com carinho de quem ama animais.',
  pos_diferenciais: 'Ex:\n1. Banho & tosa com hora marcada\n2. Veterinário todos os dias\n3. Leva e traz na região\n4. Produtos premium e naturais',
  pos_dor_principal: 'Ex: Tutores que se preocupam com o bem-estar do pet e não confiam em qualquer lugar.',
  pos_concorrentes: 'Ex:\n1. Pet shop de bairro\n2. Rede grande de pet\n3. Banho & tosa em domicílio',
  pos_jargoes_setor: 'Ex: "tosa higiênica", "tosa na máquina", "banho terapêutico", "vermífugo", "vacina V10", "castração"',
  pos_slogan: 'Ex: "Porque seu pet merece o melhor."',
  pos_o_que_nao_somos: 'Ex: Não fazemos hotel para pets. Não atendemos animais silvestres. Não vendemos filhotes.',
  pub_perfil_ideal: 'Ex: Tutores 25-50 anos que tratam o pet como família e valorizam segurança e carinho.',
  pub_perfil_nao_desejado: 'Ex: Quem busca só o banho mais barato sem se importar com a qualidade.',
  pub_ticket_medio: 'Ex: R$ 80 por banho & tosa; R$ 200 quando inclui consulta veterinária.',
  pub_dores_comuns: 'Ex:\n1. Medo de maus-tratos no banho\n2. Pet estressado/agressivo\n3. Não saber quais vacinas estão em dia\n4. Falta de tempo pra levar',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto custa o banho?"\n2. "Tem leva e traz?"\n3. "Atende pet bravo?"\n4. "Tem veterinário hoje?"',
  tom_cumprimento: 'Ex: "Oi! 🐾 Bem-vindo ao Mundo Pet! Quer agendar banho & tosa, marcar o veterinário ou ver nossos produtos?"',
  com_lista_servicos: 'Ex:\n- Banho (R$ 50-90)\n- Tosa (R$ 60-120)\n- Consulta veterinária (R$ 120)\n- Vacinas\n- Leva e traz\n- Produtos e ração',
  com_categorias: 'Ex:\n- Banho & tosa\n- Veterinário e vacinas\n- Produtos (ração, petiscos, acessórios)\n- Leva e traz',
  com_servico_premium: 'Ex: Day care + banho + spa relaxante — R$ 250/dia',
  com_combos_pacotes: 'Ex: Plano mensal de banhos (4 banhos) R$ 280; Combo banho + tosa + hidratação R$ 150',
  com_garantia: 'Ex: Se o pet não ficar bem cuidado, refazemos o banho sem custo.',
  qual_objecao_preco: 'Ex: Destacar a segurança, o profissional especializado e o plano mensal que sai mais barato.',
  pre_tabela_precos: 'Ex:\n- Banho: R$ 50-90 (porte)\n- Tosa: R$ 60-120\n- Consulta vet: R$ 120\n- Leva e traz: R$ 20',
  pre_parcelamento: 'Ex: Pix, débito e crédito; plano mensal recorrente.',
  faq_perguntas_frequentes: 'Ex:\nP: Tem leva e traz?\nR: Sim, na região, R$ 20.\nP: Quanto custa o banho?\nR: De R$ 50 a R$ 90 conforme o porte.\nP: Tem veterinário?\nR: Sim, todos os dias.',
  faq_contraindicacoes: 'Ex: Pets idosos ou com problema cardíaco passam por avaliação antes do banho; carrapaticida só com orientação.',
  crm_tags: 'Ex: #banho-tosa, #veterinario, #vacina-pendente, #leva-e-traz, #cliente-fiel',
  crm_ltv: 'Ex: R$ 1.800/ano por pet (banhos recorrentes + vet + produtos).',
};

// ── Psicologia / terapia (psicólogo) ─────────────────────────────────────────
const psicólogo: Examples = {
  ide_nome_fantasia: 'Ex: Espaço Equilíbrio Psicologia',
  ide_razao_social: 'Ex: Equilíbrio Serviços Psicológicos Ltda.',
  pos_proposta_valor: 'Ex: Terapia acolhedora e baseada em evidências, presencial ou online, no seu tempo e sem julgamento.',
  pos_diferenciais: 'Ex:\n1. Atendimento online e presencial\n2. Abordagem TCC com plano terapêutico\n3. Primeira sessão de acolhimento\n4. Horários noturnos e aos sábados',
  pos_dor_principal: 'Ex: Pessoas com ansiedade, burnout ou relacionamentos difíceis que não sabem por onde começar.',
  pos_concorrentes: 'Ex:\n1. Plataformas de terapia online\n2. Psicólogo de convênio\n3. Clínica-escola (preço baixo)',
  pos_jargoes_setor: 'Ex: "TCC", "vínculo terapêutico", "sessão de acolhimento", "psicoterapia", "ansiedade", "sigilo"',
  pos_slogan: 'Ex: "Cuidar de você também é coragem."',
  pos_o_que_nao_somos: 'Ex: Não prescrevemos medicação. Não atendemos urgência psiquiátrica. Não fazemos laudo pericial.',
  pub_perfil_ideal: 'Ex: Adultos 25-45 anos lidando com ansiedade, estresse ou transições de vida, abertos a terapia regular.',
  pub_perfil_nao_desejado: 'Ex: Quem busca solução imediata em uma sessão ou espera receita de remédio.',
  pub_ticket_medio: 'Ex: R$ 180 por sessão; R$ 640/mês no plano semanal.',
  pub_dores_comuns: 'Ex:\n1. Vergonha de pedir ajuda\n2. Dúvida se terapia funciona\n3. Preço da sessão\n4. Falta de horário na rotina',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto custa a sessão?"\n2. "Atende online?"\n3. "Aceita convênio?"\n4. "Quanto tempo dura o tratamento?"',
  tom_cumprimento: 'Ex: "Olá, seja bem-vindo(a). 🌱 Sou do Espaço Equilíbrio. Posso te ajudar a agendar uma sessão de acolhimento?"',
  com_lista_servicos: 'Ex:\n- Sessão de acolhimento\n- Psicoterapia individual (R$ 180)\n- Terapia de casal (R$ 240)\n- Atendimento online\n- Plano mensal semanal',
  com_categorias: 'Ex:\n- Terapia individual\n- Terapia de casal/família\n- Atendimento online\n- Acompanhamento de ansiedade/burnout',
  com_servico_premium: 'Ex: Plano intensivo (2 sessões/semana + acompanhamento) — R$ 1.200/mês',
  com_combos_pacotes: 'Ex: Pacote mensal (4 sessões) R$ 640; Pacote casal (4 sessões) R$ 880',
  com_garantia: 'Ex: Primeira sessão é de acolhimento — se não houver encaixe, indicamos outro profissional.',
  qual_objecao_preco: 'Ex: Explicar o valor do acompanhamento contínuo, o plano mensal e a sessão de acolhimento pra conhecer o trabalho.',
  pre_tabela_precos: 'Ex:\n- Sessão individual: R$ 180\n- Terapia de casal: R$ 240\n- Plano mensal (4x): R$ 640',
  pre_parcelamento: 'Ex: Pix, cartão e recibo para reembolso de convênio; plano mensal recorrente.',
  faq_perguntas_frequentes: 'Ex:\nP: Atende online?\nR: Sim, presencial e online por vídeo.\nP: Aceita convênio?\nR: Atendimento particular com recibo para reembolso.\nP: Quanto tempo dura?\nR: Varia por pessoa; avaliamos juntos.',
  faq_contraindicacoes: 'Ex: Casos de surto ou risco exigem encaminhamento psiquiátrico; não atendemos emergência.',
  crm_tags: 'Ex: #acolhimento, #ansiedade, #casal, #online, #plano-mensal, #reembolso',
  crm_ltv: 'Ex: R$ 4.300 ao longo do acompanhamento (sessões semanais por ~6 meses).',
};

// ── Advocacia (advogado) ─────────────────────────────────────────────────────
const advogado: Examples = {
  ide_nome_fantasia: 'Ex: Martins & Associados Advocacia',
  ide_razao_social: 'Ex: Martins Sociedade de Advogados',
  pos_proposta_valor: 'Ex: Defesa estratégica e linguagem clara — você entende cada passo do seu processo, sem juridiquês.',
  pos_diferenciais: 'Ex:\n1. Atendimento direto com o advogado responsável\n2. Atualização do processo por WhatsApp\n3. Primeira consulta de avaliação\n4. Especialização em trabalhista e cível',
  pos_dor_principal: 'Ex: Pessoas com um problema jurídico que se sentem perdidas e com medo de custos escondidos.',
  pos_concorrentes: 'Ex:\n1. Escritório grande (impessoal)\n2. Advogado autônomo\n3. Sindicato/Defensoria',
  pos_jargoes_setor: 'Ex: "petição inicial", "audiência", "honorários", "acordo", "liminar", "trabalhista", "êxito"',
  pos_slogan: 'Ex: "Seus direitos em boas mãos."',
  pos_o_que_nao_somos: 'Ex: Não atuamos em direito criminal. Não damos consultoria gratuita por telefone. Não garantimos resultado.',
  pub_perfil_ideal: 'Ex: Pessoas físicas e pequenas empresas com causas trabalhistas, cíveis ou de família.',
  pub_perfil_nao_desejado: 'Ex: Quem quer parecer jurídico só pra "ameaçar" sem intenção real de resolver.',
  pub_ticket_medio: 'Ex: R$ 350 por consulta; honorários de 20-30% sobre o êxito da causa.',
  pub_dores_comuns: 'Ex:\n1. Medo de custo alto\n2. Não entender o andamento\n3. Demora da Justiça\n4. Não saber se tem direito',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto vou pagar?"\n2. "Tenho chance de ganhar?"\n3. "Quanto tempo demora?"\n4. "Cobra mesmo se perder?"',
  tom_cumprimento: 'Ex: "Olá, bem-vindo(a) ao Martins & Associados. ⚖️ Pode me contar resumidamente seu caso para eu te orientar?"',
  com_lista_servicos: 'Ex:\n- Consulta jurídica (R$ 350)\n- Causas trabalhistas\n- Direito de família (divórcio, pensão)\n- Cível e contratos\n- Acordos extrajudiciais',
  com_categorias: 'Ex:\n- Trabalhista\n- Família\n- Cível e contratos\n- Consultoria empresarial',
  com_servico_premium: 'Ex: Assessoria jurídica mensal para empresas — a partir de R$ 2.500/mês',
  com_combos_pacotes: 'Ex: Pacote abertura de empresa (contrato + registro) R$ 1.800; Assessoria recorrente PJ',
  com_garantia: 'Ex: Honorários de êxito: você só paga o percentual se ganharmos a causa.',
  qual_objecao_preco: 'Ex: Explicar honorários de êxito, parcelamento da consulta e o risco de não agir a tempo (prescrição).',
  pre_tabela_precos: 'Ex:\n- Consulta: R$ 350\n- Honorários de êxito: 20-30%\n- Contrato simples: a partir de R$ 600',
  pre_parcelamento: 'Ex: Consulta no Pix/cartão; honorários conforme contrato; entrada + êxito.',
  faq_perguntas_frequentes: 'Ex:\nP: Cobra consulta?\nR: Sim, R$ 350, abatidos se fechar o caso.\nP: Tenho chance?\nR: Avaliamos os documentos antes de opinar.\nP: Cobra se perder?\nR: No êxito, só se ganharmos.',
  faq_contraindicacoes: 'Ex: Não atuamos em casos criminais nem damos parecer sem analisar a documentação.',
  crm_tags: 'Ex: #consulta, #trabalhista, #família, #civel, #pj, #acordo',
  crm_ltv: 'Ex: R$ 8.000 por cliente (honorários de êxito + causas recorrentes).',
};

// ── Nutrição (nutricionista) ─────────────────────────────────────────────────
const nutricionista: Examples = {
  ide_nome_fantasia: 'Ex: NutriVida Consultoria',
  ide_razao_social: 'Ex: NutriVida Nutrição e Saúde Ltda.',
  pos_proposta_valor: 'Ex: Plano alimentar que cabe na sua rotina e no seu paladar — sem dieta restritiva nem terrorismo nutricional.',
  pos_diferenciais: 'Ex:\n1. Plano individualizado (não folha genérica)\n2. Acompanhamento por app entre consultas\n3. Atende online e presencial\n4. Bioimpedância na avaliação',
  pos_dor_principal: 'Ex: Quem já tentou várias dietas, não consegue manter e quer resultado sustentável.',
  pos_concorrentes: 'Ex:\n1. Apps de dieta genéricos\n2. Nutricionista de convênio\n3. "Dietas da internet" gratuitas',
  pos_jargoes_setor: 'Ex: "bioimpedância", "reeducação alimentar", "déficit calórico", "macros", "plano alimentar", "anamnese"',
  pos_slogan: 'Ex: "Comer bem sem sofrer."',
  pos_o_que_nao_somos: 'Ex: Não prescrevemos remédio nem fórmula manipulada. Não fazemos dieta milagrosa. Não vendemos suplemento.',
  pub_perfil_ideal: 'Ex: Adultos 25-50 anos que querem emagrecer ou melhorar a saúde com acompanhamento de verdade.',
  pub_perfil_nao_desejado: 'Ex: Quem busca dieta relâmpago de 7 dias e não quer retornar pra acompanhamento.',
  pub_ticket_medio: 'Ex: R$ 250 na primeira consulta; R$ 150 nos retornos.',
  pub_dores_comuns: 'Ex:\n1. Já tentou tudo e não emagrece\n2. Não tem tempo de cozinhar\n3. Efeito sanfona\n4. Não saber o que comer',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto custa a consulta?"\n2. "Atende online?"\n3. "Vou passar fome?"\n4. "Em quanto tempo vejo resultado?"',
  tom_cumprimento: 'Ex: "Oi! 🥗 Bem-vindo(a) à NutriVida! Quer agendar sua avaliação ou tirar uma dúvida sobre o acompanhamento?"',
  com_lista_servicos: 'Ex:\n- Consulta inicial + bioimpedância (R$ 250)\n- Retorno (R$ 150)\n- Plano alimentar\n- Acompanhamento online\n- Nutrição esportiva',
  com_categorias: 'Ex:\n- Emagrecimento\n- Nutrição esportiva\n- Saúde e reeducação alimentar\n- Acompanhamento online',
  com_servico_premium: 'Ex: Programa 3 meses (consultas + retornos + suporte por app) — R$ 1.200',
  com_combos_pacotes: 'Ex: Pacote trimestral (consulta + 3 retornos) R$ 600; Plano fechado com acompanhamento por app',
  com_garantia: 'Ex: Reajustamos o plano sem custo se algo não se encaixar na sua rotina.',
  qual_objecao_preco: 'Ex: Mostrar o valor do acompanhamento contínuo e do pacote trimestral frente a consultas avulsas.',
  pre_tabela_precos: 'Ex:\n- Consulta inicial: R$ 250\n- Retorno: R$ 150\n- Pacote trimestral: R$ 600',
  pre_parcelamento: 'Ex: Pix, cartão e recibo para reembolso; pacote em até 3x.',
  faq_perguntas_frequentes: 'Ex:\nP: Atende online?\nR: Sim, presencial e online.\nP: Aceita convênio?\nR: Particular com recibo para reembolso.\nP: Vou passar fome?\nR: Não, o plano respeita seu paladar e rotina.',
  faq_contraindicacoes: 'Ex: Gestantes e pessoas com doença renal/diabetes seguem protocolo específico após avaliação.',
  crm_tags: 'Ex: #avaliação, #emagrecimento, #esportiva, #retorno, #plano-trimestral, #online',
  crm_ltv: 'Ex: R$ 1.200 por cliente (pacote trimestral + retornos).',
};

// ── Imobiliária / corretor (imobiliaria) ─────────────────────────────────────
const imobiliaria: Examples = {
  ide_nome_fantasia: 'Ex: Prime Imóveis',
  ide_razao_social: 'Ex: Prime Negócios Imobiliários Ltda.',
  pos_proposta_valor: 'Ex: Realizamos o sonho da casa própria com curadoria de imóveis, financiamento facilitado e zero burocracia escondida.',
  pos_diferenciais: 'Ex:\n1. Curadoria de imóveis pelo seu perfil\n2. Assessoria de financiamento\n3. Visitas agendadas com horário\n4. Documentação acompanhada do início ao fim',
  pos_dor_principal: 'Ex: Quem quer comprar/alugar mas se perde em anúncios desatualizados e tem medo da burocracia.',
  pos_concorrentes: 'Ex:\n1. Portais de anúncio (sem atendimento)\n2. Corretor autônomo\n3. Imobiliária tradicional do bairro',
  pos_jargoes_setor: 'Ex: "ITBI", "escritura", "financiamento", "entrada", "FGTS", "matrícula", "vistoria", "comissão"',
  pos_slogan: 'Ex: "A chave do seu próximo lar."',
  pos_o_que_nao_somos: 'Ex: Não anunciamos imóvel sem visita. Não cobramos taxa de cadastro. Não trabalhamos com imóvel irregular.',
  pub_perfil_ideal: 'Ex: Famílias e investidores 30-55 anos buscando comprar, vender ou alugar na região.',
  pub_perfil_nao_desejado: 'Ex: Curiosos que só querem saber preço sem intenção real de fechar.',
  pub_ticket_medio: 'Ex: Comissão de 6% na venda; 1 aluguel na locação.',
  pub_dores_comuns: 'Ex:\n1. Anúncios falsos/desatualizados\n2. Medo da burocracia do financiamento\n3. Não saber se o preço é justo\n4. Demora pra agendar visita',
  pub_objecoes_comuns: 'Ex:\n1. "Qual o valor da entrada?"\n2. "Aceita financiamento?"\n3. "Tem visita hoje?"\n4. "Cobra taxa de cadastro?"',
  tom_cumprimento: 'Ex: "Olá! 🏡 Bem-vindo(a) à Prime Imóveis! Está procurando comprar, alugar ou vender? Me conta o que precisa."',
  com_lista_servicos: 'Ex:\n- Venda de imóveis\n- Locação\n- Assessoria de financiamento\n- Avaliação de imóvel\n- Administração de aluguel',
  com_categorias: 'Ex:\n- Apartamentos\n- Casas\n- Comercial/salas\n- Terrenos\n- Locação',
  com_servico_premium: 'Ex: Administração completa de carteira de aluguéis para investidores',
  com_combos_pacotes: 'Ex: Pacote vendedor (avaliação + anúncio profissional + fotos + tour 360°)',
  com_garantia: 'Ex: Imóveis com documentação verificada antes do anúncio; visita sem compromisso.',
  qual_objecao_preco: 'Ex: Justificar a comissão pela curadoria, segurança jurídica e assessoria de financiamento incluída.',
  pre_tabela_precos: 'Ex:\n- Comissão venda: 6%\n- Locação: 1º aluguel\n- Administração: 8% do aluguel/mês',
  pre_parcelamento: 'Ex: Entrada + financiamento bancário; uso de FGTS; condições conforme o imóvel.',
  faq_perguntas_frequentes: 'Ex:\nP: Aceita financiamento?\nR: Sim, com assessoria gratuita.\nP: Posso usar FGTS?\nR: Sim, em imóveis elegíveis.\nP: Cobra cadastro?\nR: Não cobramos taxa de cadastro.',
  faq_contraindicacoes: 'Ex: Não trabalhamos com imóveis sem matrícula regular ou em litígio.',
  crm_tags: 'Ex: #comprador, #locatario, #investidor, #financiamento, #visita-agendada, #vendedor',
  crm_ltv: 'Ex: R$ 18.000 por cliente (comissão média de venda + indicações).',
};

// ── Escola / curso (escola) ──────────────────────────────────────────────────
const escola: Examples = {
  ide_nome_fantasia: 'Ex: Colégio Saber Mais',
  ide_razao_social: 'Ex: Instituição de Ensino Saber Mais Ltda.',
  pos_proposta_valor: 'Ex: Ensino de qualidade com acompanhamento individual, valores humanos e preparo real para o futuro do seu filho.',
  pos_diferenciais: 'Ex:\n1. Turmas reduzidas\n2. Plataforma de ensino + material próprio\n3. Período integral opcional\n4. Acompanhamento pedagógico individual',
  pos_dor_principal: 'Ex: Pais preocupados com a qualidade do ensino e o desenvolvimento socioemocional dos filhos.',
  pos_concorrentes: 'Ex:\n1. Escola pública\n2. Rede de franquias de ensino\n3. Colégio tradicional da região',
  pos_jargoes_setor: 'Ex: "BNCC", "período integral", "material didático", "matrícula", "rematrícula", "boletim", "reforço"',
  pos_slogan: 'Ex: "Educar para a vida."',
  pos_o_que_nao_somos: 'Ex: Não somos a escola mais barata. Não temos turmas gigantes. Não terceirizamos o pedagógico.',
  pub_perfil_ideal: 'Ex: Pais 30-45 anos, classe B, que priorizam qualidade de ensino e acompanhamento próximo.',
  pub_perfil_nao_desejado: 'Ex: Quem decide só pela mensalidade mais baixa, sem valorizar o projeto pedagógico.',
  pub_ticket_medio: 'Ex: R$ 1.200/mês por aluno; R$ 1.900 no integral.',
  pub_dores_comuns: 'Ex:\n1. Medo de ensino fraco\n2. Mensalidade alta\n3. Insegurança/violência\n4. Falta de acompanhamento dos pais',
  pub_objecoes_comuns: 'Ex:\n1. "Qual o valor da mensalidade?"\n2. "Tem período integral?"\n3. "Tem vaga pra série X?"\n4. "Como funciona a matrícula?"',
  tom_cumprimento: 'Ex: "Olá! 📚 Bem-vindo(a) ao Colégio Saber Mais! Quer informações sobre matrícula, valores ou agendar uma visita?"',
  com_lista_servicos: 'Ex:\n- Educação Infantil\n- Ensino Fundamental\n- Ensino Médio\n- Período integral\n- Reforço e atividades extras',
  com_categorias: 'Ex:\n- Educação Infantil\n- Fundamental I e II\n- Ensino Médio\n- Integral e extracurriculares',
  com_servico_premium: 'Ex: Período integral com atividades bilíngues e esportivas — R$ 1.900/mês',
  com_combos_pacotes: 'Ex: Desconto progressivo por irmão; matrícula antecipada com material incluso',
  com_garantia: 'Ex: Período de adaptação acompanhado; reunião pedagógica nas primeiras semanas.',
  qual_objecao_preco: 'Ex: Mostrar turmas reduzidas, acompanhamento individual, descontos por irmão e o que está incluso (material/plataforma).',
  pre_tabela_precos: 'Ex:\n- Educação Infantil: R$ 1.100\n- Fundamental: R$ 1.200\n- Médio: R$ 1.400\n- Integral: +R$ 700',
  pre_parcelamento: 'Ex: Matrícula + 12 mensalidades; material à vista ou parcelado; desconto pontualidade.',
  faq_perguntas_frequentes: 'Ex:\nP: Tem vaga?\nR: Consulte a série; algumas têm lista de espera.\nP: Tem integral?\nR: Sim, opcional.\nP: Como matriculo?\nR: Agende uma visita e traga os documentos.',
  faq_contraindicacoes: 'Ex: Matrícula sujeita à disponibilidade de vaga e à entrega da documentação completa.',
  crm_tags: 'Ex: #matricula, #visita-agendada, #integral, #irmao, #rematricula, #lista-espera',
  crm_ltv: 'Ex: R$ 130.000 por aluno (ciclo completo de vários anos).',
};

// ── Serviços técnicos / assistência (servicos_tecnicos) ──────────────────────
const servicos_tecnicos: Examples = {
  ide_nome_fantasia: 'Ex: TecFix Assistência Técnica',
  ide_razao_social: 'Ex: TecFix Serviços e Reparos Ltda.',
  pos_proposta_valor: 'Ex: Conserto rápido e com garantia — orçamento transparente antes de qualquer reparo, sem surpresa na conta.',
  pos_diferenciais: 'Ex:\n1. Orçamento antes do reparo\n2. Garantia de 90 dias no serviço\n3. Atendimento no local ou retira & entrega\n4. Peças originais',
  pos_dor_principal: 'Ex: Quem teve equipamento quebrado e tem medo de ser enganado no orçamento ou no prazo.',
  pos_concorrentes: 'Ex:\n1. Assistência da marca (caro/lento)\n2. Técnico autônomo informal\n3. Loja de conserto sem garantia',
  pos_jargoes_setor: 'Ex: "orçamento", "diagnóstico", "garantia", "peça original", "OS (ordem de serviço)", "retira e entrega"',
  pos_slogan: 'Ex: "Conserto certo, sem dor de cabeça."',
  pos_o_que_nao_somos: 'Ex: Não cobramos sem aprovar orçamento. Não usamos peça paralela sem avisar. Não fazemos reparo sem garantia.',
  pub_perfil_ideal: 'Ex: Residências e pequenas empresas que precisam de conserto confiável com garantia.',
  pub_perfil_nao_desejado: 'Ex: Quem só quer o orçamento mais barato e questiona qualquer garantia.',
  pub_ticket_medio: 'Ex: R$ 220 por atendimento; R$ 450 quando troca peça.',
  pub_dores_comuns: 'Ex:\n1. Medo de ser enganado no preço\n2. Demora pro conserto ficar pronto\n3. Não saber se vale consertar\n4. Conserto que não dura',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto custa pra consertar?"\n2. "Tem garantia?"\n3. "Pra quando fica pronto?"\n4. "Cobra a visita?"',
  tom_cumprimento: 'Ex: "Olá! 🔧 Bem-vindo(a) à TecFix! Me conta qual equipamento precisa de reparo que eu já te oriento sobre o orçamento."',
  com_lista_servicos: 'Ex:\n- Diagnóstico/orçamento\n- Reparo de eletrodomésticos\n- Conserto de eletrônicos\n- Atendimento no local\n- Retira e entrega',
  com_categorias: 'Ex:\n- Eletrodomésticos\n- Eletrônicos\n- Instalação\n- Manutenção preventiva',
  com_servico_premium: 'Ex: Contrato de manutenção preventiva para empresas — mensal',
  com_combos_pacotes: 'Ex: Combo manutenção (limpeza + revisão) com desconto; pacote empresa',
  com_garantia: 'Ex: 90 dias de garantia em peças e serviço; refazemos se o problema voltar.',
  qual_objecao_preco: 'Ex: Destacar orçamento prévio, peças originais e garantia de 90 dias frente ao "barato que não dura".',
  pre_tabela_precos: 'Ex:\n- Diagnóstico: R$ 80 (abatido no reparo)\n- Visita técnica: R$ 120\n- Reparo: conforme orçamento',
  pre_parcelamento: 'Ex: Pix, débito e crédito; reparos acima de R$ 300 em 2x.',
  faq_perguntas_frequentes: 'Ex:\nP: Cobra a visita?\nR: R$ 120, abatidos se aprovar o reparo.\nP: Tem garantia?\nR: 90 dias.\nP: Pra quando fica?\nR: Em média 2-3 dias após aprovação.',
  faq_contraindicacoes: 'Ex: Equipamentos com dano por líquido ou já abertos por terceiros podem não ter garantia.',
  crm_tags: 'Ex: #orcamento, #aguardando-aprovação, #garantia, #empresa, #retorno',
  crm_ltv: 'Ex: R$ 900 por cliente (reparos recorrentes + manutenção).',
};

// ── Clínica médica / estética (clinica_medica) ───────────────────────────────
const clinica_medica: Examples = {
  ide_nome_fantasia: 'Ex: Clínica Vida & Saúde',
  ide_razao_social: 'Ex: Vida & Saúde Serviços Médicos Ltda.',
  pos_proposta_valor: 'Ex: Atendimento médico humanizado, exames no mesmo lugar e agenda que respeita o seu horário.',
  pos_diferenciais: 'Ex:\n1. Consulta + exames no mesmo dia\n2. Múltiplas especialidades\n3. Telemedicina disponível\n4. Resultados pelo portal do paciente',
  pos_dor_principal: 'Ex: Pacientes cansados de fila de convênio e de esperar semanas por uma consulta.',
  pos_concorrentes: 'Ex:\n1. Rede de clínicas populares\n2. Hospital (convênio)\n3. Consultório individual',
  pos_jargoes_setor: 'Ex: "consulta", "retorno", "exame", "encaminhamento", "telemedicina", "especialidade", "convênio"',
  pos_slogan: 'Ex: "Sua saúde em primeiro lugar."',
  pos_o_que_nao_somos: 'Ex: Não somos pronto-socorro 24h. Não fazemos cirurgia de grande porte. Não atendemos urgência grave.',
  pub_perfil_ideal: 'Ex: Famílias e adultos que querem atendimento ágil e de qualidade, com ou sem convênio.',
  pub_perfil_nao_desejado: 'Ex: Quem busca apenas atestado rápido sem avaliação clínica.',
  pub_ticket_medio: 'Ex: R$ 300 por consulta particular; pacotes de check-up a partir de R$ 600.',
  pub_dores_comuns: 'Ex:\n1. Demora pra conseguir consulta\n2. Ter que ir em vários lugares pra exames\n3. Não saber o preço\n4. Atendimento corrido',
  pub_objecoes_comuns: 'Ex:\n1. "Atende meu convênio?"\n2. "Quanto é a consulta particular?"\n3. "Tem horário hoje?"\n4. "Faz o exame aqui mesmo?"',
  tom_cumprimento: 'Ex: "Olá! 🩺 Bem-vindo(a) à Clínica Vida & Saúde! Posso ajudar a agendar consulta, exame ou tirar dúvidas sobre convênio?"',
  com_lista_servicos: 'Ex:\n- Consultas (várias especialidades)\n- Exames laboratoriais\n- Check-up\n- Telemedicina\n- Pequenos procedimentos',
  com_categorias: 'Ex:\n- Clínica geral\n- Especialidades\n- Exames e check-up\n- Telemedicina',
  com_servico_premium: 'Ex: Check-up executivo completo (consultas + exames + retorno) — R$ 1.500',
  com_combos_pacotes: 'Ex: Pacote check-up básico R$ 600; plano família com desconto em consultas',
  com_garantia: 'Ex: Retorno incluso em até 30 dias após a consulta, sem custo adicional.',
  qual_objecao_preco: 'Ex: Comparar com a fila do convênio, destacar consulta + exame no mesmo dia e os pacotes de check-up.',
  pre_tabela_precos: 'Ex:\n- Consulta particular: R$ 300\n- Retorno: incluso (30 dias)\n- Check-up básico: R$ 600',
  pre_parcelamento: 'Ex: Pix, cartão e convênios; pacotes de check-up em até 3x.',
  faq_perguntas_frequentes: 'Ex:\nP: Atende convênio?\nR: Sim, vários — confirme o seu.\nP: Faz exame no local?\nR: Sim, coleta no mesmo endereço.\nP: Tem retorno?\nR: Incluso em até 30 dias.',
  faq_contraindicacoes: 'Ex: Casos de urgência/emergência devem procurar pronto-socorro; alguns exames exigem preparo.',
  crm_tags: 'Ex: #consulta, #exame, #check-up, #convenio, #retorno, #telemedicina',
  crm_ltv: 'Ex: R$ 3.000/ano por paciente (consultas + exames recorrentes).',
};

// ── Contabilidade (contabilidade) ────────────────────────────────────────────
const contabilidade: Examples = {
  ide_nome_fantasia: 'Ex: Contábil Resultado',
  ide_razao_social: 'Ex: Resultado Assessoria Contábil Ltda.',
  pos_proposta_valor: 'Ex: Sua contabilidade em dia e sem dor de cabeça — economia tributária de verdade e um contador que fala a sua língua.',
  pos_diferenciais: 'Ex:\n1. Contador dedicado por cliente\n2. Portal online com seus documentos\n3. Planejamento tributário ativo\n4. Resposta em até 1 dia útil',
  pos_dor_principal: 'Ex: Empreendedores que se perdem com impostos, prazos e burocracia e têm medo de multa.',
  pos_concorrentes: 'Ex:\n1. Contabilidade online de massa\n2. Escritório tradicional sem tecnologia\n3. Contador autônomo',
  pos_jargoes_setor: 'Ex: "Simples Nacional", "DAS", "pró-labore", "folha", "DRE", "MEI", "obrigações acessórias", "regime tributário"',
  pos_slogan: 'Ex: "Sua empresa em ordem, seu lucro protegido."',
  pos_o_que_nao_somos: 'Ex: Não somos despachante. Não fazemos "caixa dois". Não atrasamos obrigações fiscais.',
  pub_perfil_ideal: 'Ex: Pequenas e médias empresas e profissionais liberais que querem regularidade e economia tributária.',
  pub_perfil_nao_desejado: 'Ex: Quem busca só o menor honorário e quer práticas fora da lei.',
  pub_ticket_medio: 'Ex: R$ 600/mês de honorário; abertura de empresa R$ 1.200.',
  pub_dores_comuns: 'Ex:\n1. Medo de multa/atraso\n2. Pagar imposto demais\n3. Não entender o contador\n4. Demora nas respostas',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto custa o honorário?"\n2. "Faz abertura de empresa?"\n3. "Atende meu regime?"\n4. "Como troco de contador?"',
  tom_cumprimento: 'Ex: "Olá! 📊 Bem-vindo(a) à Contábil Resultado! Quer abrir empresa, trocar de contador ou tirar uma dúvida fiscal?"',
  com_lista_servicos: 'Ex:\n- Abertura de empresa\n- Contabilidade mensal\n- Folha de pagamento\n- Imposto de Renda PF/PJ\n- Planejamento tributário',
  com_categorias: 'Ex:\n- Abertura e regularização\n- Contabilidade mensal\n- Folha e RH\n- Tributário e IR',
  com_servico_premium: 'Ex: Planejamento tributário + BPO financeiro para empresas em crescimento',
  com_combos_pacotes: 'Ex: Combo abertura + 3 meses de honorário; pacote MEI; pacote IR pessoa física',
  com_garantia: 'Ex: Se houver multa por erro nosso, arcamos com o custo.',
  qual_objecao_preco: 'Ex: Mostrar a economia tributária gerada, o risco de multa e o contador dedicado frente à contabilidade de massa.',
  pre_tabela_precos: 'Ex:\n- Honorário mensal: a partir de R$ 600\n- Abertura de empresa: R$ 1.200\n- IR pessoa física: R$ 250',
  pre_parcelamento: 'Ex: Honorário mensal recorrente; abertura em 2x; Pix com desconto.',
  faq_perguntas_frequentes: 'Ex:\nP: Faz abertura de empresa?\nR: Sim, e cuidamos de toda a documentação.\nP: Atende Simples Nacional?\nR: Sim, e os demais regimes.\nP: Como troco de contador?\nR: Cuidamos da migração pra você.',
  faq_contraindicacoes: 'Ex: Não realizamos práticas irregulares; regularização de pendências antigas é orçada à parte.',
  crm_tags: 'Ex: #abertura, #troca-contador, #mei, #simples, #ir, #folha',
  crm_ltv: 'Ex: R$ 21.600 por cliente (honorário recorrente ao longo de 3 anos).',
};

// ── Oficina / autocenter (oficina) ───────────────────────────────────────────
const oficina: Examples = {
  ide_nome_fantasia: 'Ex: AutoCenter Veloz',
  ide_razao_social: 'Ex: Veloz Serviços Automotivos Ltda.',
  pos_proposta_valor: 'Ex: Seu carro pronto no prazo, com orçamento transparente e garantia no serviço — sem peça empurrada.',
  pos_diferenciais: 'Ex:\n1. Orçamento por foto/vídeo antes\n2. Garantia de 90 dias no serviço\n3. Carro reserva ou leva & traz\n4. Mecânicos certificados',
  pos_dor_principal: 'Ex: Donos de carro que têm medo de oficina que enrola, troca peça à toa e cobra a mais.',
  pos_concorrentes: 'Ex:\n1. Concessionária (caro)\n2. Mecânico de esquina\n3. Rede de autocenter',
  pos_jargoes_setor: 'Ex: "revisão", "alinhamento", "balanceamento", "injeção eletrônica", "scanner", "OS", "garantia de serviço"',
  pos_slogan: 'Ex: "Seu carro em boas mãos."',
  pos_o_que_nao_somos: 'Ex: Não trocamos peça sem aprovar. Não cobramos diagnóstico escondido. Não fazemos funilaria/pintura.',
  pub_perfil_ideal: 'Ex: Donos de carro 25-55 anos que valorizam confiança, prazo e garantia.',
  pub_perfil_nao_desejado: 'Ex: Quem só quer o preço mais baixo e desconfia de qualquer recomendação.',
  pub_ticket_medio: 'Ex: R$ 350 numa revisão; R$ 900 quando troca peças.',
  pub_dores_comuns: 'Ex:\n1. Medo de ser enganado\n2. Carro parado por dias\n3. Peça trocada sem necessidade\n4. Orçamento que muda no final',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto custa a revisão?"\n2. "Tem garantia?"\n3. "Pra quando fica pronto?"\n4. "Cobra o diagnóstico?"',
  tom_cumprimento: 'Ex: "Fala! 🚗 Bem-vindo(a) ao AutoCenter Veloz! Me conta o que o carro está apresentando que eu já te oriento."',
  com_lista_servicos: 'Ex:\n- Revisão completa\n- Troca de óleo\n- Freios e suspensão\n- Alinhamento e balanceamento\n- Diagnóstico eletrônico (scanner)',
  com_categorias: 'Ex:\n- Manutenção preventiva\n- Mecânica geral\n- Elétrica e injeção\n- Pneus e geometria',
  com_servico_premium: 'Ex: Revisão completa com checklist de 30 itens + scanner — pacote fechado',
  com_combos_pacotes: 'Ex: Combo revisão (óleo + filtros + checklist) com desconto; pacote troca de pneus',
  com_garantia: 'Ex: 90 dias de garantia em peças e mão de obra.',
  qual_objecao_preco: 'Ex: Mostrar orçamento prévio, garantia de 90 dias e o risco de rodar com o problema (peça maior depois).',
  pre_tabela_precos: 'Ex:\n- Troca de óleo: a partir de R$ 180\n- Revisão: a partir de R$ 350\n- Diagnóstico scanner: R$ 90',
  pre_parcelamento: 'Ex: Pix, débito e crédito; serviços acima de R$ 500 em até 3x.',
  faq_perguntas_frequentes: 'Ex:\nP: Cobra o diagnóstico?\nR: R$ 90, abatido se aprovar o serviço.\nP: Tem garantia?\nR: 90 dias.\nP: Pra quando fica?\nR: Revisão simples no mesmo dia.',
  faq_contraindicacoes: 'Ex: Não fazemos funilaria/pintura nem reparo de câmbio automático complexo (encaminhamos parceiro).',
  crm_tags: 'Ex: #revisao, #orcamento, #aguardando-aprovação, #garantia, #retorno, #troca-oleo',
  crm_ltv: 'Ex: R$ 2.400/ano por cliente (revisões + manutenções recorrentes).',
};

// ── Agência digital / marketing (agencia_digital) ────────────────────────────
const agencia_digital: Examples = {
  ide_nome_fantasia: 'Ex: Pixel Agência Digital',
  ide_razao_social: 'Ex: Pixel Marketing Digital Ltda.',
  pos_proposta_valor: 'Ex: Marketing digital orientado a resultado — tráfego, conteúdo e dados que viram venda, não só "likes".',
  pos_diferenciais: 'Ex:\n1. Foco em ROI, não em vaidade\n2. Relatórios claros e reuniões mensais\n3. Time dedicado por conta\n4. Gestão de tráfego + conteúdo + social',
  pos_dor_principal: 'Ex: Empresas que já gastaram com agência e não viram retorno claro do investimento.',
  pos_concorrentes: 'Ex:\n1. Freelancer avulso\n2. Agência grande (impessoal)\n3. "Sobrinho" que mexe em rede social',
  pos_jargoes_setor: 'Ex: "ROI", "ROAS", "tráfego pago", "CPL", "funil", "lead", "CTA", "landing page", "remarketing"',
  pos_slogan: 'Ex: "Resultado que você mede."',
  pos_o_que_nao_somos: 'Ex: Não vendemos seguidor falso. Não prometemos viralizar. Não trabalhamos sem briefing e meta clara.',
  pub_perfil_ideal: 'Ex: Pequenas e médias empresas que querem escalar vendas com previsibilidade e dados.',
  pub_perfil_nao_desejado: 'Ex: Quem quer só "post bonito" sem meta de venda ou orçamento de mídia.',
  pub_ticket_medio: 'Ex: R$ 2.500/mês de fee + verba de mídia à parte.',
  pub_dores_comuns: 'Ex:\n1. Já gastou e não viu retorno\n2. Não entende relatório de agência\n3. Medo de jogar dinheiro fora em anúncio\n4. Falta de previsibilidade',
  pub_objecoes_comuns: 'Ex:\n1. "Quanto custa por mês?"\n2. "Tem contrato de fidelidade?"\n3. "Em quanto tempo dá resultado?"\n4. "A verba de anúncio é à parte?"',
  tom_cumprimento: 'Ex: "Olá! 🚀 Bem-vindo(a) à Pixel! Me conta seu objetivo (mais leads, mais vendas?) que eu te mostro como podemos ajudar."',
  com_lista_servicos: 'Ex:\n- Gestão de tráfego pago\n- Social media\n- Criação de conteúdo\n- Landing pages\n- Consultoria de funil',
  com_categorias: 'Ex:\n- Tráfego pago (Meta/Google)\n- Social media e conteúdo\n- Sites e landing pages\n- Branding',
  com_servico_premium: 'Ex: Gestão completa (tráfego + social + conteúdo + CRM) — a partir de R$ 6.000/mês',
  com_combos_pacotes: 'Ex: Pacote Start (tráfego + 1 landing) R$ 2.500/mês; Pacote Full',
  com_garantia: 'Ex: Primeiro mês com diagnóstico e metas acordadas; sem fidelidade longa.',
  qual_objecao_preco: 'Ex: Mostrar projeção de ROI, casos de clientes e separar fee de gestão da verba de mídia.',
  pre_tabela_precos: 'Ex:\n- Pacote Start: R$ 2.500/mês\n- Pacote Full: R$ 6.000/mês\n- Verba de mídia: à parte',
  pre_parcelamento: 'Ex: Fee mensal recorrente (boleto/cartão/Pix); verba de mídia paga direto na plataforma.',
  faq_perguntas_frequentes: 'Ex:\nP: A verba de anúncio é à parte?\nR: Sim, o fee é a gestão; a mídia é separada.\nP: Tem fidelidade?\nR: Ciclo mínimo de 3 meses.\nP: Quando vejo resultado?\nR: Otimização real a partir do 2º mês.',
  faq_contraindicacoes: 'Ex: Resultado depende de verba de mídia adequada e produto/oferta validados.',
  crm_tags: 'Ex: #lead-quente, #tráfego, #social, #proposta, #onboarding, #cliente-recorrente',
  crm_ltv: 'Ex: R$ 30.000 por cliente (fee mensal ao longo de ~12 meses).',
};

// ── E-commerce / loja online (ecommerce) ─────────────────────────────────────
const ecommerce: Examples = {
  ide_nome_fantasia: 'Ex: Loja Bella Moda',
  ide_razao_social: 'Ex: Bella Moda Comércio Online Ltda.',
  pos_proposta_valor: 'Ex: Produtos selecionados, entrega rápida e troca fácil — a comodidade de comprar online com atendimento de loja de bairro.',
  pos_diferenciais: 'Ex:\n1. Envio em até 24h\n2. Troca grátis em 30 dias\n3. Atendimento humano no WhatsApp\n4. Frete grátis acima de R$ 199',
  pos_dor_principal: 'Ex: Clientes com receio de comprar online — medo de errar tamanho, atraso na entrega e dor de cabeça na troca.',
  pos_concorrentes: 'Ex:\n1. Grandes marketplaces\n2. Lojas de fast fashion\n3. Importados do exterior',
  pos_jargoes_setor: 'Ex: "frete", "rastreio", "código de envio", "troca", "estorno", "cupom", "carrinho abandonado", "SKU"',
  pos_slogan: 'Ex: "Seu estilo, entregue na sua porta."',
  pos_o_que_nao_somos: 'Ex: Não vendemos réplica. Não temos loja física. Não fazemos entrega no mesmo dia em todo o país.',
  pub_perfil_ideal: 'Ex: Mulheres 20-40 anos que compram pelo celular e valorizam praticidade e troca fácil.',
  pub_perfil_nao_desejado: 'Ex: Quem busca só o preço de marketplace gigante e não valoriza atendimento.',
  pub_ticket_medio: 'Ex: R$ 180 por pedido; R$ 250 quando usa cupom de combo.',
  pub_dores_comuns: 'Ex:\n1. Medo de errar o tamanho\n2. Atraso na entrega\n3. Dificuldade pra trocar\n4. Insegurança no pagamento',
  pub_objecoes_comuns: 'Ex:\n1. "Qual o prazo de entrega?"\n2. "Como faço a troca?"\n3. "Tem frete grátis?"\n4. "É seguro pagar no site?"',
  tom_cumprimento: 'Ex: "Oi! 🛍️ Bem-vindo(a) à Bella Moda! Quer ajuda pra escolher um produto, rastrear seu pedido ou fazer uma troca?"',
  com_lista_servicos: 'Ex:\n- Catálogo de produtos\n- Rastreio de pedido\n- Troca e devolução\n- Cupons e promoções\n- Atendimento pós-venda',
  com_categorias: 'Ex:\n- Roupas\n- Calçados\n- Acessórios\n- Lançamentos / promoções',
  com_servico_premium: 'Ex: Clube de assinatura com frete grátis e acesso a lançamentos antecipados',
  com_combos_pacotes: 'Ex: Leve 3 pague 2; combo look completo com desconto; cupom primeira compra',
  com_garantia: 'Ex: Troca grátis em 30 dias e devolução do valor se não gostar.',
  qual_objecao_preco: 'Ex: Destacar frete grátis acima de R$ 199, troca grátis, parcelamento e cupom de primeira compra.',
  pre_tabela_precos: 'Ex:\n- Ticket médio: R$ 180\n- Frete grátis: acima de R$ 199\n- Cupom 1ª compra: 10% off',
  pre_parcelamento: 'Ex: Cartão em até 6x sem juros, Pix com 5% off, boleto.',
  faq_perguntas_frequentes: 'Ex:\nP: Qual o prazo de entrega?\nR: 24h pra postar + prazo dos Correios.\nP: Como troco?\nR: Troca grátis em 30 dias pelo WhatsApp.\nP: Tem frete grátis?\nR: Sim, acima de R$ 199.',
  faq_contraindicacoes: 'Ex: Produtos íntimos e personalizados não têm troca; consulte a política completa.',
  crm_tags: 'Ex: #carrinho-abandonado, #rastreio, #troca, #cupom, #cliente-recorrente, #primeira-compra',
  crm_ltv: 'Ex: R$ 720/ano por cliente (compras recorrentes + recompra).',
};

export const NICHE_EXAMPLES: Record<string, Examples> = {
  restaurante,
  dentista,
  salao,
  academia,
  petshop,
  psicólogo,
  advogado,
  nutricionista,
  imobiliaria,
  escola,
  servicos_tecnicos,
  clinica_medica,
  contabilidade,
  oficina,
  agencia_digital,
  ecommerce,
};

/**
 * Resolve o placeholder de exemplo para um campo do survey, dado o niche da org.
 * Ordem: exemplo do niche > exemplo neutro (GENERIC) > placeholder original.
 */
export function examplePlaceholder(
  niche: string | undefined | null,
  questionId: string,
  fallback?: string,
): string | undefined {
  const n = (niche || '').trim().toLowerCase();
  return NICHE_EXAMPLES[n]?.[questionId] ?? GENERIC[questionId] ?? fallback;
}
