#!/bin/bash
# =========================================================
# ZappIQ — Comandos Pré-Launch (Executar antes de D-Day)
# Gerado em: 2026-04-16
# =========================================================
#
# INSTRUÇÕES: Execute cada bloco na ordem. Cada bloco é
# independente — se um falhar, corrija e siga pro próximo.
#
# =========================================================

echo "=== BLOCO 1: Fly.io Secrets (faltantes) ==="
echo ""
echo "Setar SENTRY_DSN (criar projeto em sentry.io primeiro):"
echo "  fly secrets set SENTRY_DSN='https://<key>@<org>.ingest.us.sentry.io/<project-id>' -a zappiq-api"
echo ""
echo "Setar RESEND_API_KEY (pegar em resend.com/api-keys):"
echo "  fly secrets set RESEND_API_KEY='re_xxxxx' -a zappiq-api"
echo ""
echo "Setar EMAIL_FROM e EMAIL_REPLY_TO:"
echo "  fly secrets set EMAIL_FROM='ZappIQ <hello@zappiq.com.br>' EMAIL_REPLY_TO='founders@zappiq.com.br' -a zappiq-api"
echo ""

echo "=== BLOCO 2: Vercel Environment Variables (PostHog) ==="
echo ""
echo "Executar no terminal (requer vercel CLI logado):"
echo "  cd apps/web"
echo "  vercel env add NEXT_PUBLIC_POSTHOG_API_KEY production <<< 'phc_kgDvBBcdwZusHHGSMakek9J8bzLxWGcyA2gzmoFqqzpP'"
echo "  vercel env add NEXT_PUBLIC_POSTHOG_HOST production <<< 'https://us.i.posthog.com'"
echo "  vercel env add POSTHOG_API_KEY production <<< 'phc_kgDvBBcdwZusHHGSMakek9J8bzLxWGcyA2gzmoFqqzpP'"
echo ""
echo "OU configurar diretamente no dashboard Vercel:"
echo "  https://vercel.com → Settings → Environment Variables"
echo ""

echo "=== BLOCO 3: Deploy com fly.toml corrigido ==="
echo ""
echo "O fly.toml agora usa 'prisma migrate deploy' em vez de 'prisma db push'."
echo "Comitar e redeployar:"
echo "  git add fly.toml apps/web/components/shared/CookieBanner.tsx apps/web/app/layout.tsx apps/web/lib/track.ts apps/web/.env.local"
echo "  git commit -m 'fix: migrate deploy + LGPD cookie banner + PostHog env'"
echo "  fly deploy -a zappiq-api"
echo ""

echo "=== BLOCO 4: Validação Pós-Deploy ==="
echo ""
echo "Rodar smoke test:"
echo "  bash scripts/smoke-staging.sh"
echo ""
echo "Verificar cookie banner no frontend:"
echo "  Abrir https://zappiq.vercel.app em aba anônima"
echo "  Banner deve aparecer na parte inferior"
echo "  Clicar 'Aceitar todos' → banner desaparece"
echo "  Refresh → banner não reaparece"
echo ""

echo "=== BLOCO 5: Itens Manuais Pendentes ==="
echo ""
echo "[ ] Criar projeto Sentry (sentry.io) e pegar DSN"
echo "[ ] Criar API Key no Resend (resend.com) e configurar domínio zappiq.com.br"
echo "[ ] Configurar Cloudflare DNS apontando para Fly.io e Vercel"
echo "[ ] Stripe: enviar documentos de identidade (Rodrigo handling)"
echo "[ ] Testar webhook WhatsApp Business API de ponta a ponta"
echo "[ ] Validar backup Supabase (Pro plan) com restore test"
echo "[ ] Fazer dry-run completo do fluxo: landing → register → onboarding → AI training → WhatsApp"
echo ""

echo "=== RESUMO DO GO/NO-GO STATUS ==="
echo ""
echo "PRONTO:"
echo "  ✓ API deployada no Fly.io (9/9 smoke tests passando)"
echo "  ✓ Rate limiting (global 500/15min + auth 10/15min)"
echo "  ✓ CORS configurado para domínios de produção"
echo "  ✓ Prisma migrate deploy (não mais db push)"
echo "  ✓ Email templates (5 templates Resend)"
echo "  ✓ Rollback plan documentado (RUNBOOK + INCIDENT-RESPONSE)"
echo "  ✓ Legal pages (/termos, /privacidade, /dpa)"
echo "  ✓ Cookie consent banner LGPD"
echo "  ✓ PostHog analytics integrado (client + server)"
echo "  ✓ Staging DB populado (10 orgs + superadmin)"
echo "  ✓ Press kit (brand guidelines + logos)"
echo "  ✓ 30 convites beta preparados"
echo "  ✓ SSL via Fly.io (force_https)"
echo "  ✓ Rolling deploys (min 2 machines)"
echo ""
echo "PENDENTE (requer ação manual):"
echo "  ○ Sentry DSN → fly secrets set"
echo "  ○ Resend API Key → fly secrets set"
echo "  ○ PostHog env vars → Vercel dashboard"
echo "  ○ Stripe identity docs → Rodrigo"
echo "  ○ WhatsApp Business API webhook test"
echo "  ○ Cloudflare DNS config"
echo "  ○ Dry-run completo do fluxo"
echo ""
echo "D-Day: 30 de abril de 2026"
echo "Go/No-Go meeting: 29 de abril, 14:00 SP"
