/**
 * FLOW_TEMPLATES_DATA — fonte unica dos 15 templates Maestro V1.
 *
 * Usado por:
 *   - packages/database/prisma/seeds/flowTemplates.ts (seed manual)
 *   - apps/api/src/bootstrap/seedFlowTemplates.ts (bootstrap startup)
 *
 * Sem prisma calls aqui — so a estrutura de dados.
 */

import type { FlowTemplateVertical, FlowTemplateCategory, FlowTriggerType } from '@prisma/client';

export interface FlowTemplateSeed {
  name: string;
  description: string;
  vertical: FlowTemplateVertical;
  category: FlowTemplateCategory;
  nodes: any[];
  edges: any[];
  triggerType: FlowTriggerType;
  order: number;
  isActive: boolean;
}

function n(id: string, type: string, x: number, y: number, label: string, extra: Record<string, any> = {}) {
  return { id, type, position: { x, y }, data: { label, ...extra } };
}
function e(source: string, target: string, label?: string) {
  return { id: `e-${source}-${target}`, source, target, ...(label ? { label } : {}) };
}
function T(
  v: FlowTemplateVertical,
  c: FlowTemplateCategory,
  name: string,
  description: string,
  nodes: any[],
  edges: any[],
  triggerType: FlowTriggerType,
  order: number
): FlowTemplateSeed {
  return { name, description, vertical: v, category: c, nodes, edges, triggerType, order, isActive: true };
}

export const FLOW_TEMPLATES_DATA: FlowTemplateSeed[] = [
  // ═══ DENTISTA ═══
  T('DENTISTA', 'BOAS_VINDAS_QUALIFICACAO',
    'Dentista — Boas-vindas + Qualificacao',
    'Recebe lead novo, apresenta a clinica, qualifica intencao (avaliacao, urgencia, estetica, ortodontia) e direciona pra proxima acao.',
    [
      n('1', 'input', 100, 100, 'Lead chegou'),
      n('2', 'message', 100, 200, 'Saudacao', { message: 'Oi! Sou a Iza da Clinica X. Como posso ajudar?' }),
      n('3', 'ai_node', 100, 320, 'Iza qualifica', { intent: 'identificar tipo de demanda (avaliacao, urgencia, estetica, ortodontia)' }),
      n('4', 'condition', 100, 460, 'Tipo de demanda?'),
      n('5a', 'message', 0, 600, 'Avaliacao', { message: 'Avaliacao gratuita disponivel. Posso agendar?' }),
      n('5b', 'message', 200, 600, 'Urgencia', { message: 'Entendi a urgencia. Temos hora hoje as 14h ou 16h. Qual prefere?' }),
      n('6', 'action', 100, 740, 'Marcar lead score', { action: 'update_lead_score', score: 60 }),
      n('7', 'human_handoff', 100, 880, 'Passa pra recepcao'),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5a','avaliacao'), e('4','5b','urgencia'), e('5a','6'), e('5b','6'), e('6','7') ],
    'FIRST_CONTACT', 1),

  T('DENTISTA', 'AGENDAMENTO_RECUPERACAO',
    'Dentista — Agendamento + Recuperacao 24h',
    'Cliente nao retornou apos 24h da primeira conversa. Iza dispara follow-up oferecendo agendar com lembrete de horario livre.',
    [
      n('1', 'input', 100, 100, 'Inativo 24h'),
      n('2', 'message', 100, 220, 'Lembrete', { message: 'Oi! Vi que voce tinha interesse em avaliacao. Ainda quer agendar?' }),
      n('3', 'ai_node', 100, 360, 'Iza ouve resposta', { intent: 'aceita ou recusa agendamento' }),
      n('4', 'condition', 100, 500, 'Aceitou?'),
      n('5a', 'action', 0, 640, 'Agenda Google', { action: 'create_calendar_event' }),
      n('5b', 'action', 200, 640, 'Salva nao interessado', { action: 'update_lead_status', status: 'NOT_INTERESTED' }),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5a','sim'), e('4','5b','nao') ],
    'TIMEOUT_24H', 2),

  T('DENTISTA', 'NPS_POS_VENDA',
    'Dentista — NPS pos-consulta',
    'Apos consulta finalizada, manda NPS 1-10. Promotores (>=9) recebem pedido de review Google; detratores ganham contato humano.',
    [
      n('1', 'input', 100, 100, 'Consulta finalizada'),
      n('2', 'message', 100, 220, 'NPS', { message: 'Como foi sua experiencia hoje? De 0 a 10' }),
      n('3', 'ai_node', 100, 360, 'Coleta nota', { intent: 'extrair nota NPS 0-10' }),
      n('4', 'condition', 100, 500, 'Nota >= 9?'),
      n('5a', 'message', 0, 640, 'Promotor', { message: 'Que otimo! Deixaria review aqui? <link Google>' }),
      n('5b', 'message', 200, 640, 'Detrator/Neutro', { message: 'Obrigada! Posso te ajudar com algo?' }),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5a','promotor'), e('4','5b','detrator') ],
    'CUSTOM', 3),

  // ═══ SALAO BELEZA ═══
  T('SALAO_BELEZA', 'BOAS_VINDAS_QUALIFICACAO',
    'Salao — Boas-vindas + Qualificacao',
    'Recebe lead, apresenta servicos (corte/coloracao/escova/manicure), qualifica preferencia de profissional e horario.',
    [
      n('1', 'input', 100, 100, 'Lead chegou'),
      n('2', 'message', 100, 220, 'Saudacao', { message: 'Oi! Sou a Iza do Salao X.' }),
      n('3', 'ai_node', 100, 360, 'Qualifica servico', { intent: 'corte, coloracao, escova, manicure' }),
      n('4', 'condition', 100, 500, 'Profissional preferida?'),
      n('5', 'message', 100, 640, 'Apresenta agenda', { message: 'Temos horarios essa semana. Qual dia prefere?' }),
      n('6', 'human_handoff', 100, 780, 'Recepcao confirma'),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5'), e('5','6') ],
    'FIRST_CONTACT', 4),

  T('SALAO_BELEZA', 'AGENDAMENTO_RECUPERACAO',
    'Salao — Recuperacao 48h',
    'Cliente que nao agendou em 48h recebe oferta com 10% off no primeiro corte.',
    [
      n('1', 'input', 100, 100, 'Inativo 48h'),
      n('2', 'message', 100, 220, 'Oferta', { message: 'Saudades! 10% off no seu primeiro corte essa semana' }),
      n('3', 'ai_node', 100, 360, 'Iza confirma', { intent: 'aceita oferta?' }),
      n('4', 'action', 100, 500, 'Aplica cupom', { action: 'create_coupon', discount: 10 }),
      n('5', 'human_handoff', 100, 640, 'Agendamento humano'),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ],
    'TIMEOUT_48H', 5),

  T('SALAO_BELEZA', 'NPS_POS_VENDA',
    'Salao — NPS pos-servico',
    'Apos servico, manda NPS + pede foto resultado pra Instagram (com permissao). Detratores ganham contato pessoal.',
    [
      n('1', 'input', 100, 100, 'Servico finalizado'),
      n('2', 'message', 100, 220, 'NPS', { message: 'Curtiu o resultado? De 0 a 10' }),
      n('3', 'ai_node', 100, 360, 'Coleta nota'),
      n('4', 'condition', 100, 500, 'Nota >= 9?'),
      n('5a', 'message', 0, 640, 'Pede foto', { message: 'Adorei! Posso compartilhar foto no Insta marcando voce?' }),
      n('5b', 'message', 200, 640, 'Detrator', { message: 'Posso te chamar pra entender melhor?' }),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5a','promotor'), e('4','5b','detrator') ],
    'CUSTOM', 6),

  // ═══ ACADEMIA ═══
  T('ACADEMIA', 'BOAS_VINDAS_QUALIFICACAO',
    'Academia — Boas-vindas + Aula experimental',
    'Lead novo recebe oferta de aula experimental gratis + qualifica objetivo (emagrecimento, hipertrofia, condicionamento).',
    [
      n('1', 'input', 100, 100, 'Lead chegou'),
      n('2', 'message', 100, 220, 'Saudacao', { message: 'Oi! Aqui e a Iza da Academia X. Aula experimental gratuita pra voce!' }),
      n('3', 'ai_node', 100, 360, 'Qualifica objetivo', { intent: 'emagrecimento, hipertrofia, condicionamento, outro' }),
      n('4', 'message', 100, 500, 'Pede dia/horario', { message: 'Qual dia e horario voce prefere pra fazer a experimental?' }),
      n('5', 'action', 100, 640, 'Agenda experimental'),
      n('6', 'human_handoff', 100, 780, 'Recepcao confirma'),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5'), e('5','6') ],
    'FIRST_CONTACT', 7),

  T('ACADEMIA', 'AGENDAMENTO_RECUPERACAO',
    'Academia — Recuperacao membro inativo 14d',
    'Membro que parou de frequentar ha 14 dias recebe mensagem motivacional + oferta de 1 sessao gratis com personal trainer.',
    [
      n('1', 'input', 100, 100, 'Inativo 14d'),
      n('2', 'message', 100, 220, 'Motivacao', { message: 'Tudo bem? Vimos que voce nao tem vindo. Posso te ajudar a voltar?' }),
      n('3', 'ai_node', 100, 360, 'Detecta motivo', { intent: 'preguica, falta de tempo, dor, sem motivacao' }),
      n('4', 'message', 100, 500, 'Oferece PT gratis', { message: 'Que tal 1 sessao gratis com personal pra retomar? Eu agendo' }),
      n('5', 'action', 100, 640, 'Agenda PT'),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ],
    'TIMEOUT_14D', 8),

  T('ACADEMIA', 'NPS_POS_VENDA',
    'Academia — NPS mensal',
    'Mensalmente, manda NPS pra membros ativos + pergunta sugestao melhoria. Alimenta cohort de retencao.',
    [
      n('1', 'input', 100, 100, 'Cron mensal'),
      n('2', 'message', 100, 220, 'NPS', { message: 'Como foi seu mes? De 0 a 10' }),
      n('3', 'ai_node', 100, 360, 'Coleta nota + sugestao', { intent: 'extrair NPS + sugestao' }),
      n('4', 'action', 100, 500, 'Salva resposta', { action: 'save_nps_response' }),
    ],
    [ e('1','2'), e('2','3'), e('3','4') ],
    'CUSTOM', 9),

  // ═══ PETSHOP ═══
  T('PETSHOP', 'BOAS_VINDAS_QUALIFICACAO',
    'Petshop — Boas-vindas + Cadastro do pet',
    'Lead novo, pergunta nome do tutor + nome do pet + raca + idade pra cadastrar e personalizar futuras conversas.',
    [
      n('1', 'input', 100, 100, 'Lead chegou'),
      n('2', 'message', 100, 220, 'Saudacao', { message: 'Oi! Sou a Iza do Petshop X. Qual o nome do seu pet?' }),
      n('3', 'ai_node', 100, 360, 'Coleta nome+raca+idade', { intent: 'extrair dados do pet' }),
      n('4', 'action', 100, 500, 'Cadastra pet', { action: 'create_contact_with_pet' }),
      n('5', 'message', 100, 640, 'Oferta primeira visita', { message: 'Que fofo! Banho+tosa com 15% off pra primeira visita?' }),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ],
    'FIRST_CONTACT', 10),

  T('PETSHOP', 'AGENDAMENTO_RECUPERACAO',
    'Petshop — Reagendamento banho mensal',
    'Cliente que fez banho ha 30 dias recebe lembrete + oferta de reagendar com o mesmo profissional.',
    [
      n('1', 'input', 100, 100, 'Cron 30d apos banho'),
      n('2', 'message', 100, 220, 'Lembrete', { message: 'Hora do banho mensal do {nome_pet}? Posso agendar' }),
      n('3', 'ai_node', 100, 360, 'Iza confirma'),
      n('4', 'action', 100, 500, 'Agenda banho'),
    ],
    [ e('1','2'), e('2','3'), e('3','4') ],
    'TIMEOUT_30D', 11),

  T('PETSHOP', 'NPS_POS_VENDA',
    'Petshop — NPS apos servico',
    'Manda foto + NPS apos banho/tosa. Promotores ganham 5% off na proxima visita.',
    [
      n('1', 'input', 100, 100, 'Banho finalizado'),
      n('2', 'message', 100, 220, 'Manda foto + NPS', { message: 'Olha como ficou! De 0 a 10, gostou?' }),
      n('3', 'ai_node', 100, 360, 'Coleta nota'),
      n('4', 'condition', 100, 500, 'Nota >= 9?'),
      n('5', 'action', 100, 640, 'Aplica cupom 5%', { action: 'create_coupon', discount: 5 }),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5','promotor') ],
    'CUSTOM', 12),

  // ═══ ECOMMERCE MODA ═══
  T('ECOMMERCE_MODA', 'BOAS_VINDAS_QUALIFICACAO',
    'E-com Moda — Boas-vindas + Cupom primeira compra',
    'Lead novo recebe boas-vindas + cupom 10% off primeira compra + pergunta estilo (casual/festa/trabalho) pra recomendar pecas.',
    [
      n('1', 'input', 100, 100, 'Lead chegou'),
      n('2', 'message', 100, 220, 'Cupom', { message: 'Bem-vinda! Cupom PRIMEIRA10 pra 10% off' }),
      n('3', 'ai_node', 100, 360, 'Qualifica estilo', { intent: 'casual, festa, trabalho, outro' }),
      n('4', 'message', 100, 500, 'Recomendacao', { message: 'Olha umas pecas que combinam com seu estilo! <link catalogo>' }),
    ],
    [ e('1','2'), e('2','3'), e('3','4') ],
    'FIRST_CONTACT', 13),

  T('ECOMMERCE_MODA', 'AGENDAMENTO_RECUPERACAO',
    'E-com Moda — Recuperacao carrinho abandonado 2h',
    'Cliente colocou produto no carrinho mas nao finalizou em 2h. Iza dispara com oferta de frete gratis.',
    [
      n('1', 'input', 100, 100, 'Carrinho abandonado 2h'),
      n('2', 'message', 100, 220, 'Carrinho', { message: 'Vi que voce ficou interessada em {produto}. Frete gratis se finalizar hoje!' }),
      n('3', 'ai_node', 100, 360, 'Iza ouve'),
      n('4', 'condition', 100, 500, 'Aceita?'),
      n('5', 'message', 100, 640, 'Link checkout', { message: 'Aqui o link: {checkout_url}?coupon=FRETE_GRATIS' }),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5','sim') ],
    'CART_ABANDONED', 14),

  T('ECOMMERCE_MODA', 'NPS_POS_VENDA',
    'E-com Moda — NPS pos-entrega',
    'Apos confirmacao de entrega (rastreio mostrado como ENTREGUE), manda NPS + pede foto pra Insta.',
    [
      n('1', 'input', 100, 100, 'Pedido entregue'),
      n('2', 'message', 100, 220, 'Chegou?', { message: 'Chegou! De 0 a 10, gostou?' }),
      n('3', 'ai_node', 100, 360, 'Coleta nota'),
      n('4', 'condition', 100, 500, 'Nota >= 9?'),
      n('5', 'message', 100, 640, 'Pede foto', { message: 'Que bom! Manda foto vestida pra eu repostar no Insta marcando voce?' }),
    ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5','promotor') ],
    'CUSTOM', 15),

  // PATCH B — 11 verticais × 3 jornadas = 33 templates
  T('PSICOLOGO' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Psicologia — Acolhimento + Qualificacao',
    'Recebe interessado, acolhe com empatia, qualifica demanda e oferece avaliacao.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Acolhe',{message:'Oi, que bom voce buscar ajuda. Como posso te ajudar?'}), n('3','ai_node',100,360,'Qualifica',{intent:'foco'}), n('4','message',100,500,'Oferta avaliacao'), n('5','human_handoff',100,640,'Confirma') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 16),
  T('PSICOLOGO' as any, 'AGENDAMENTO_RECUPERACAO',
    'Psicologia — Reagendamento sessao perdida',
    'Paciente faltou — mensagem empatica e reagenda.',
    [ n('1','input',100,100,'Sessao perdida'), n('2','message',100,220,'Reagendamento'), n('3','ai_node',100,360,'Aceita?'), n('4','action',100,500,'Agenda') ],
    [ e('1','2'), e('2','3'), e('3','4') ], 'CUSTOM', 17),
  T('PSICOLOGO' as any, 'NPS_POS_VENDA',
    'Psicologia — Check-in pos-sessao',
    'Apos sessao, check-in delicado sem cobrar NPS direto.',
    [ n('1','input',100,100,'Sessao finalizada'), n('2','message',100,220,'Como esta?'), n('3','ai_node',100,360,'Feedback livre') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 18),

  T('ADVOGADO' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Advocacia — Triagem area + Reuniao',
    'Identifica area juridica e agenda reuniao paga.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Apresentacao'), n('3','ai_node',100,360,'Area',{intent:'area'}), n('4','message',100,500,'Reuniao paga'), n('5','human_handoff',100,640,'Advogado') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 19),
  T('ADVOGADO' as any, 'AGENDAMENTO_RECUPERACAO',
    'Advocacia — Resgate prazo decisivo',
    'Lead com prazo iminente que nao agendou — reforco urgencia.',
    [ n('1','input',100,100,'Inativo 24h + prazo'), n('2','message',100,220,'Urgencia'), n('3','ai_node',100,360,'Confirma'), n('4','human_handoff',100,500,'Advogado') ],
    [ e('1','2'), e('2','3'), e('3','4') ], 'TIMEOUT_24H', 20),
  T('ADVOGADO' as any, 'NPS_POS_VENDA',
    'Advocacia — NPS pos-causa',
    'Apos sentenca ou acordo, NPS + review Google.',
    [ n('1','input',100,100,'Caso encerrado'), n('2','message',100,220,'NPS'), n('3','ai_node',100,360,'Nota'), n('4','condition',100,500,'>=9?'), n('5','message',100,640,'Pede Google') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5','promotor') ], 'CUSTOM', 21),

  T('NUTRICIONISTA' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Nutricao — Avaliacao + Objetivo',
    'Pergunta objetivo e oferece avaliacao.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Saudacao'), n('3','ai_node',100,360,'Objetivo'), n('4','message',100,500,'Oferta'), n('5','human_handoff',100,640,'Recepcao') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 22),
  T('NUTRICIONISTA' as any, 'AGENDAMENTO_RECUPERACAO',
    'Nutricao — Retorno 30d',
    'Convite pra retorno 30d apos plano.',
    [ n('1','input',100,100,'Cron 30d'), n('2','message',100,220,'Retorno'), n('3','ai_node',100,360,'Aceita'), n('4','action',100,500,'Agenda') ],
    [ e('1','2'), e('2','3'), e('3','4') ], 'TIMEOUT_30D', 23),
  T('NUTRICIONISTA' as any, 'NPS_POS_VENDA',
    'Nutricao — Check-in semanal',
    'Acompanhamento semanal de adesao.',
    [ n('1','input',100,100,'Semanal'), n('2','message',100,220,'Como foi a semana?'), n('3','ai_node',100,360,'Adesao') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 24),

  T('IMOBILIARIA' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Imobiliaria — Qualificacao BANT',
    'Coleta tipo + bairro + ticket + prazo.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Saudacao'), n('3','ai_node',100,360,'BANT'), n('4','action',100,500,'Lead score'), n('5','human_handoff',100,640,'Corretor') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 25),
  T('IMOBILIARIA' as any, 'AGENDAMENTO_RECUPERACAO',
    'Imobiliaria — Reaviso visita',
    'Lembrete 24h antes da visita.',
    [ n('1','input',100,100,'Visita 24h'), n('2','message',100,220,'Lembrete'), n('3','ai_node',100,360,'Confirma') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 26),
  T('IMOBILIARIA' as any, 'NPS_POS_VENDA',
    'Imobiliaria — NPS pos-visita',
    'Apos visita, feedback + proximos passos.',
    [ n('1','input',100,100,'Visita finalizada'), n('2','message',100,220,'Feedback'), n('3','ai_node',100,360,'Coleta') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 27),

  T('RESTAURANTE' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Restaurante — Reserva + Cardapio',
    'Reserva via WA com cardapio enviado automatico.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Saudacao'), n('3','ai_node',100,360,'Data/pessoas'), n('4','action',100,500,'Reserva'), n('5','message',100,640,'Cardapio') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 28),
  T('RESTAURANTE' as any, 'AGENDAMENTO_RECUPERACAO',
    'Restaurante — Lembrete reserva',
    'Lembrete 3h antes.',
    [ n('1','input',100,100,'Reserva 3h'), n('2','message',100,220,'Lembrete') ],
    [ e('1','2') ], 'CUSTOM', 29),
  T('RESTAURANTE' as any, 'NPS_POS_VENDA',
    'Restaurante — NPS pos-refeicao',
    'NPS + pede review Google se promotor.',
    [ n('1','input',100,100,'Conta paga'), n('2','message',100,220,'NPS'), n('3','ai_node',100,360,'Nota'), n('4','condition',100,500,'>=9?'), n('5','message',100,640,'Pede review') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5','promotor') ], 'CUSTOM', 30),

  T('ESCOLA' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Escola — Matricula + Visita',
    'Coleta idade/serie e agenda visita guiada.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Saudacao'), n('3','ai_node',100,360,'Perfil'), n('4','message',100,500,'Convite visita'), n('5','human_handoff',100,640,'Recepcao') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 31),
  T('ESCOLA' as any, 'AGENDAMENTO_RECUPERACAO',
    'Escola — Reuniao pais lembrete',
    'Lembrete 48h antes.',
    [ n('1','input',100,100,'48h antes'), n('2','message',100,220,'Lembrete'), n('3','ai_node',100,360,'Confirma') ],
    [ e('1','2'), e('2','3') ], 'TIMEOUT_48H', 32),
  T('ESCOLA' as any, 'NPS_POS_VENDA',
    'Escola — NPS semestral',
    'NPS semestral pra pais.',
    [ n('1','input',100,100,'Semestral'), n('2','message',100,220,'NPS'), n('3','ai_node',100,360,'Coleta') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 33),

  T('SERVICOS_TECNICOS' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Servicos — Orcamento + Visita',
    'Coleta descricao + foto e agenda visita.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Saudacao'), n('3','ai_node',100,360,'Descricao'), n('4','action',100,500,'Orcamento'), n('5','human_handoff',100,640,'Tecnico') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 34),
  T('SERVICOS_TECNICOS' as any, 'AGENDAMENTO_RECUPERACAO',
    'Servicos — Reaviso visita tecnica',
    'Lembrete 2h antes.',
    [ n('1','input',100,100,'2h antes'), n('2','message',100,220,'Lembrete'), n('3','ai_node',100,360,'Confirma') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 35),
  T('SERVICOS_TECNICOS' as any, 'NPS_POS_VENDA',
    'Servicos — NPS pos-servico',
    'NPS + cupom 10% recompra.',
    [ n('1','input',100,100,'Servico'), n('2','message',100,220,'NPS'), n('3','ai_node',100,360,'Nota'), n('4','condition',100,500,'>=9?'), n('5','action',100,640,'Cupom') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5','promotor') ], 'CUSTOM', 36),

  T('CLINICA_MEDICA' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Clinica Medica — Triagem + Agendamento',
    'Especialidade + convenio + agenda.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Saudacao'), n('3','ai_node',100,360,'Especialidade'), n('4','message',100,500,'Agenda'), n('5','human_handoff',100,640,'Recepcao') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 37),
  T('CLINICA_MEDICA' as any, 'AGENDAMENTO_RECUPERACAO',
    'Clinica Medica — Confirmacao consulta',
    '24h antes + envia preparo.',
    [ n('1','input',100,100,'24h antes'), n('2','message',100,220,'Lembrete'), n('3','ai_node',100,360,'Confirma') ],
    [ e('1','2'), e('2','3') ], 'TIMEOUT_24H', 38),
  T('CLINICA_MEDICA' as any, 'NPS_POS_VENDA',
    'Clinica Medica — NPS pos-consulta',
    'NPS + Doctoralia review.',
    [ n('1','input',100,100,'Consulta'), n('2','message',100,220,'NPS'), n('3','ai_node',100,360,'Nota'), n('4','condition',100,500,'>=9?'), n('5','message',100,640,'Doctoralia') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5','promotor') ], 'CUSTOM', 39),

  T('CONTABILIDADE' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Contabilidade — Qualifica porte + Reuniao',
    'Identifica porte e agenda consultoria.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Saudacao'), n('3','ai_node',100,360,'Porte'), n('4','message',100,500,'Reuniao'), n('5','human_handoff',100,640,'Contador') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 40),
  T('CONTABILIDADE' as any, 'AGENDAMENTO_RECUPERACAO',
    'Contabilidade — Reaviso DARF',
    'Lembrete DARF vence 5d.',
    [ n('1','input',100,100,'Imposto 5d'), n('2','message',100,220,'Vencimento'), n('3','ai_node',100,360,'Pagou?') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 41),
  T('CONTABILIDADE' as any, 'NPS_POS_VENDA',
    'Contabilidade — NPS mensal',
    'NPS mensal pra carteira.',
    [ n('1','input',100,100,'Mensal'), n('2','message',100,220,'NPS'), n('3','ai_node',100,360,'Nota') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 42),

  T('OFICINA' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Oficina — Diagnostico + Orcamento',
    'Modelo + sintoma + agenda diagnostico.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Saudacao'), n('3','ai_node',100,360,'Modelo'), n('4','message',100,500,'Diagnostico'), n('5','human_handoff',100,640,'Mecanico') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 43),
  T('OFICINA' as any, 'AGENDAMENTO_RECUPERACAO',
    'Oficina — Lembrete revisao',
    'Convite revisao semestral.',
    [ n('1','input',100,100,'6m apos'), n('2','message',100,220,'Lembrete'), n('3','ai_node',100,360,'Aceita'), n('4','action',100,500,'Agenda') ],
    [ e('1','2'), e('2','3'), e('3','4') ], 'CUSTOM', 44),
  T('OFICINA' as any, 'NPS_POS_VENDA',
    'Oficina — NPS pos-servico',
    'NPS + cupom 5% recompra.',
    [ n('1','input',100,100,'Servico'), n('2','message',100,220,'NPS'), n('3','ai_node',100,360,'Nota'), n('4','condition',100,500,'>=9?'), n('5','action',100,640,'Cupom 5%') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5','promotor') ], 'CUSTOM', 45),

  T('AGENCIA_DIGITAL' as any, 'BOAS_VINDAS_QUALIFICACAO',
    'Agencia — Qualificacao MQL + Discovery',
    'Servico + faturamento + agenda call discovery.',
    [ n('1','input',100,100,'Lead'), n('2','message',100,220,'Saudacao'), n('3','ai_node',100,360,'MQL'), n('4','message',100,500,'Discovery'), n('5','human_handoff',100,640,'Closer') ],
    [ e('1','2'), e('2','3'), e('3','4'), e('4','5') ], 'FIRST_CONTACT', 46),
  T('AGENCIA_DIGITAL' as any, 'AGENDAMENTO_RECUPERACAO',
    'Agencia — Resgate proposta enviada',
    'Followup 5d apos proposta sem resposta.',
    [ n('1','input',100,100,'Proposta 5d'), n('2','message',100,220,'Followup'), n('3','ai_node',100,360,'Objecao') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 47),
  T('AGENCIA_DIGITAL' as any, 'NPS_POS_VENDA',
    'Agencia — NPS mensal carteira',
    'NPS mensal pra retainers ativos.',
    [ n('1','input',100,100,'Mensal'), n('2','message',100,220,'NPS'), n('3','ai_node',100,360,'Nota+sugestao') ],
    [ e('1','2'), e('2','3') ], 'CUSTOM', 48),
];
